### ISSUE TITLE
delete single  connected elements

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/oceanmesh#16]
* port a function that iteratively removes what we term "single connected elements" and friends
original implementation here: https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/utilities/Fix_single_connec_edge_elements.m

**Comment by CHLNDDEV** [comment]
An initial attempt at this is producing holes in the mesh. The face_to_face function is likely to blame. Also need a unit test.

**Comment by CHLNDDEV** [comment]
Fixed in #15
