### ISSUE TITLE
Slack link no longer active

### ISSUE THREAD

**Issue by ml14je** [CHLNDDEV/oceanmesh#38]
Hi there. Looking to download and use oceanmesh for generating a triangular mesh for my DG-FEM code for modelling flow in and around submarine canyons, given by some fluid-depth function varying in space. I am however having issues with getting oceanmesh to install and work on my windows machine, and could benefit from help. Unfortunately, the slack channel link you posted seems to no longer be active.

**Comment by krober10nd** [comment]
Hey sorry about that they only last for one month by default 

Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/oceanmesh2d/shared_invite/zt-vbqpk84l-wyzhVyWVkmKgGLZ37SPhug

I’ll update it on the readme. 

For windows, I would use WSL2 and install Ubuntu. It works overall well but we can talk about it on the slack.
