### ISSUE TITLE
Question: How the meshgen works

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [CHLNDDEV/oceanmesh#57]
@WPringle, do any points get generated in the mesh gen code other than the ones initially created? 
https://github.com/CHLNDDEV/oceanmesh/blob/b763b1a531961c5a0278036299dc0504a8260e98/oceanmesh/mesh_generator.py#L146

**Comment by krober10nd** [comment]
no, they do not.

**Comment by SorooshMani-NOAA** [comment]
Thanks @krober10nd, I have another question. How is the `lock_boundary` enforced? It just add stuff to `ifix` which is not used anywhere:
https://github.com/CHLNDDEV/oceanmesh/blob/b763b1a531961c5a0278036299dc0504a8260e98/oceanmesh/mesh_generator.py#L246-L249

**Comment by krober10nd** [comment]
I probably an oversight. The idea is this finds the node nearest to the fixed point and doesn't move it.

**Comment by SorooshMani-NOAA** [comment]
I see, thanks, I'll close the ticket for now since I don't have any other questions about `generate_mesh`.
