### ISSUE TITLE
black version update makes CI fail

### ISSUE THREAD

**Issue by tomsail** [CHLNDDEV/oceanmesh#77]
@jcharris @krober10nd @sgriffithjones I see you had the same linting issue in the CI lint with black : 

```
would reformat /home/runner/work/oceanmesh/oceanmesh/oceanmesh/idw.py
would reformat /home/runner/work/oceanmesh/oceanmesh/oceanmesh/geodata.py

Oh no! 💥 💔 💥
2 files would be reformatted, 29 files would be left unchanged.
```

I see 2 options here: 
  1. [correct](https://github.com/tomsail/oceanmesh/commit/bc3cbf43bba1043eeb28e8f8e3be9e9aa51424b4) the scripts that fail
  2. Downgrade black version for python 3.10 [here](https://github.com/CHLNDDEV/oceanmesh/blob/dc969ff02348d47106382a4d50c33c28a4564565/.github/workflows/testing.yml#L15) 
 
 I guess 1 is the best one in the long run. I think we should also update black locally for `python 3.11`

**Comment by pmav99** [comment]
black should format files based on the minimum supported version (i.e. python 3.7) , not the maximum.
