### ISSUE TITLE
Inquiry About Full Implementation of Matlab-Based Functions in Python Version of OceanMesh

### ISSUE THREAD

**Issue by firesinger82** [CHLNDDEV/oceanmesh#80]
Hello,

Thank you for your work on the development and improvement of OceanMesh.

I am currently studying OceanMesh and am curious to know if the functions of the Matlab-based version are fully implemented in the Python version.

**Comment by q1165600785** [comment]
I think it can be achieved, but the workload may be a bit heavy

**Comment by q1165600785** [comment]
Does the author have any plans? Implementation of Matlab Based Functions in Python Version of OceanMesh. I really need the Python version of the grid generation program

**Comment by krober10nd** [comment]
Isn't that what this repository is? 

I no longer have unpaid time to dedicate to open source projects. 

I've been working with Aquaveo in a re-write here which is integrated through the community version of SMS with plugins. https://github.com/krober10nd/SMSOceanMeshToolkit/tree/tool-development

**Comment by q1165600785** [comment]
Thank you for your selfless dedication and hard work, big shot

**Comment by krober10nd** [comment]
I hope your message is  not sarcastic. I will accept the compliment and interpret it as such.

The reason the repository exists here is for others to contribute like yourself and the OP.

**Comment by q1165600785** [comment]
Thank you for your response, I hope to contribute my own efforts in the future use
